# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 5 (который лекция). Операции с датафреймами Pandas: теория

In [1]:
import pandas as pd

In [2]:
beasts = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyReg26/refs/heads/main/fbeasts.csv")

In [3]:
# выводим первые 10 строк таблицы

beasts.head(10)

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
5,Common Welsh Green,Dragon,XXXXX,Green,No data,Wales,216.0,1
6,Hebridean Black,Dragon,XXXXX,Dark,Brilliant purple,Scotland,360.0,1
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1
8,Norwegian Ridgeback,Dragon,XXXXX,Dark green,No data,Norway,NaN,1
9,Peruvian Vipertooth,Dragon,XXXXX,Copper,No data,Peru,180.0,1

### Сортировка строк

In [4]:
beasts.sort_values("Size").head(3)

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
67,Chizpurfle,Chizpurfle,XX,Brown|Green,Black,World-wide,0.05,0
70,Fairy,Fairy,XX,Varies,Varies,World-wide,3.00,0
74,Imp,Imp,XX,Grey,Yellow,Great Britain|Ireland,7.00,0

In [5]:
beasts.sort_values("Size").tail(3)

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0

In [6]:
beasts.sort_values("Size", ascending = False).head(3)

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
10,Romanian Longhorn,Dragon,XXXXX,Dark green,No data,Romania,480.0,1

In [7]:
sorted(["1.jpeg", "3.jpeg", "10.jpeg", "2.jpeg"])

['1.jpeg', '10.jpeg', '2.jpeg', '3.jpeg']

In [8]:
beasts.sort_values(["Classification", "Size"])

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.00,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0
67,Chizpurfle,Chizpurfle,XX,Brown|Green,Black,World-wide,0.05,0
70,Fairy,Fairy,XX,Varies,Varies,World-wide,3.00,0
74,Imp,Imp,XX,Grey,Yellow,Great Britain|Ireland,7.00,0
...,...,...,...,...,...,...,...,...
13,Lethifold,Lethifold,XXXXX,Black,No data,The tropics,NaN,0
14,Manticore,Manticore,XXXXX,Golden,No data,Greece,NaN,0
15,Nundu,Nundu,XXXXX,Yellow|Black,No data,East Africa,NaN,0
16,Quintaped,Quintaped,XXXXX,Red-brown,No data,Isle of Drear,NaN,0
17,Werewolf,Werewolf,XXXXX,Varies,Varies,World-wide,NaN,0

In [9]:
beasts.sort_values(["Classification", "Size"], 
                  ascending = [True, False])

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0
73,Grindylow,Grindylow,XX,Sickly green,Yellow|White|Green,Great Britain|Ireland,60.0,0
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0
72,Gnome,Gnome,XX,Brown|Lime,No data,Europe|North America,12.0,0
...,...,...,...,...,...,...,...,...
13,Lethifold,Lethifold,XXXXX,Black,No data,The tropics,NaN,0
14,Manticore,Manticore,XXXXX,Golden,No data,Greece,NaN,0
15,Nundu,Nundu,XXXXX,Yellow|Black,No data,East Africa,NaN,0
16,Quintaped,Quintaped,XXXXX,Red-brown,No data,Isle of Drear,NaN,0
17,Werewolf,Werewolf,XXXXX,Varies,Varies,World-wide,NaN,0

In [10]:
columns = input().split()
print(columns)
beasts.sort_values(columns)

Size Classification
['Size', 'Classification']

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
67,Chizpurfle,Chizpurfle,XX,Brown|Green,Black,World-wide,0.05,0
70,Fairy,Fairy,XX,Varies,Varies,World-wide,3.00,0
74,Imp,Imp,XX,Grey,Yellow,Great Britain|Ireland,7.00,0
66,Bowtruckle,Bowtruckle,XX,Green,Brown,England|Germany|Scandinavia,8.00,0
58,Pixie,Pixie,XXX,Electric Blue,Black,England,8.00,0
...,...,...,...,...,...,...,...,...
13,Lethifold,Lethifold,XXXXX,Black,No data,The tropics,NaN,0
14,Manticore,Manticore,XXXXX,Golden,No data,Greece,NaN,0
15,Nundu,Nundu,XXXXX,Yellow|Black,No data,East Africa,NaN,0
16,Quintaped,Quintaped,XXXXX,Red-brown,No data,Isle of Drear,NaN,0
17,Werewolf,Werewolf,XXXXX,Varies,Varies,World-wide,NaN,0

### Описание данных и поиск пропусков

In [11]:
# размерность таблицы: число строк и столбцов

print(beasts.shape)
print(beasts.shape[0])
print(beasts.shape[1])

(81, 8)
81
8

In [12]:
beasts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            81 non-null     object
 1   Class           81 non-null     object
 2   Classification  81 non-null     object
 3   Colour          81 non-null     object
 4   Eye             80 non-null     object
 5   Native          81 non-null     object
 6   Size            28 non-null     float64
 7   Dragon          81 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.2+ KB

In [13]:
# типы столбцов

beasts.dtypes

Name               object
Class              object
Classification     object
Colour             object
Eye                object
Native             object
Size              float64
Dragon              int64
dtype: object

In [14]:
# выбор столбцов определенных типов

beasts.select_dtypes(int)

    Dragon
0        0
1        0
2        0
3        1
4        1
..     ...
76       0
77       0
78       0
79       0
80       0

[81 rows x 1 columns]

In [15]:
# выбор столбцов определенных типов

beasts.select_dtypes([int, float])

     Size  Dragon
0   180.0       0
1   600.0       0
2     NaN       0
3     NaN       1
4   300.0       1
..    ...     ...
76    NaN       0
77   24.0       0
78    NaN       0
79   10.0       0
80    NaN       0

[81 rows x 2 columns]

In [16]:
# вычисление числа пропусков в каждом столбце

beasts.isna().sum()

Name               0
Class              0
Classification     0
Colour             0
Eye                1
Native             0
Size              53
Dragon             0
dtype: int64

In [17]:
# удаление строк с пропусками
# удаляются строки, где есть хотя бы один пропуск

beasts = beasts.dropna()
print(beasts.shape)

(28, 8)

In [18]:
# то же самое

beasts = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyReg26/refs/heads/main/fbeasts.csv")
beasts.dropna(inplace = True)

In [19]:
beasts.shape

(28, 8)

In [20]:
# удаление строк с пропусками
# удаляются строки, где есть пропуски в столбцу Eye

beasts = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyReg26/refs/heads/main/fbeasts.csv")
beasts = beasts.dropna(subset = ["Eye"])
print(beasts.shape)

(80, 8)

### Добавление новых столбцов

In [21]:
# домножаем столбец на число и добавляем в таблицу
# с названием Size_cm

beasts["Size_cm"] = beasts["Size"] * 2.54
beasts

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon,Size_cm
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0,457.20
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0,1524.00
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0,NaN
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1,NaN
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1,762.00
...,...,...,...,...,...,...,...,...,...
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0,NaN
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0,60.96
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0,NaN
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0,25.40
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0,NaN

In [22]:
# проверяем условие, получаем столбец из True/False,
# превращаем их в 1 и 0, превращая столбец в целочисленный int

beasts["Danger"] = (beasts["Classification"] == "XXXXX").astype(int)
beasts

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon,Size_cm,Danger
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0,457.20,1
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0,1524.00,1
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0,NaN,1
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1,NaN,1
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1,762.00,1
...,...,...,...,...,...,...,...,...,...,...
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0,NaN,0
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0,60.96,0
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0,NaN,0
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0,25.40,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0,NaN,0

In [23]:
# считаем количество символов в каждой ячейке
# текстового столбца Classification

beasts["ClassNum"] = beasts["Classification"].str.len()
beasts

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon,Size_cm,Danger,ClassNum
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0,457.20,1,5
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0,1524.00,1,5
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0,NaN,1,5
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1,NaN,1,5
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1,762.00,1,5
...,...,...,...,...,...,...,...,...,...,...,...
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0,NaN,0,2
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0,60.96,0,2
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0,NaN,0,2
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0,25.40,0,1
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0,NaN,0,1

In [24]:
# в str много разных функций,
# делаем все буквы маленькими - lower()

beasts["Classification"].str.lower()

0     xxxxx
1     xxxxx
2     xxxxx
3     xxxxx
4     xxxxx
      ...
76       xx
77       xx
78       xx
79        x
80        x
Name: Classification, Length: 80, dtype: object

In [25]:
# в str много разных функций,
# проверяем вхождение подстроки Russia в ячейки с текстом

beasts["Native"].str.contains("Russia")

0     False
1     False
2     False
3     False
4     False
      ...
76    False
77    False
78    False
79    False
80    False
Name: Native, Length: 80, dtype: bool

In [26]:
# подставляем True/False выше
# в фильтр и отбираем строки с Russia в Native

beasts[beasts["Native"].str.contains("Russia")]

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon,Size_cm,Danger,ClassNum
57,Nogtail,Nogtail,XXX,No data,Black,Europe|Russia|North America|South America,NaN,0,NaN,0,3
60,Pogrebin,Pogrebin,XXX,No data,No data,Russia,NaN,0,NaN,0,3