# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 4. Введение в датафреймы Pandas

### Немного теории: загрузка данных и их описание

На этом семинаре мы будем работать с данными из файла `fbeasts.csv` (скачать [здесь](https://github.com/allatambov/PyReg26/blob/main/fbeasts.csv)), который содержит
характеристики фантастических существ. Показатели в файле:

* `Name`: название существа;
* `Class`: класс существа (если есть, если нет, дублируется название); 
* `Classification`: классификация Министерства Магии;
* `Colour`: цвет тела;
* `Eye`: цвет глаз;
* `Native`: происхождение и распространение;
* `Size`: размер в дюймах;
* `Dragon`: является ли существо драконом (1 – да, 0 – нет).

Импортируем библиотеку `pandas` и загрузим данные из файла `fbeasts.csv` в датафрейм `df`:

In [1]:
import pandas as pd

In [2]:
# вариант 1
df = pd.read_csv("fbeasts.csv")
df

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
...,...,...,...,...,...,...,...,...
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0

In [3]:
# вариант 2
# по ссылке на сырой файл

df = pd.read_csv("https://raw.githubusercontent.com/allatambov/PyReg26/refs/heads/main/fbeasts.csv")
df

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
2,Chimaera,Chimaera,XXXXX,Golden,White,Greece,NaN,0
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
...,...,...,...,...,...,...,...,...
76,Mooncalf,Mooncalf,XX,Pink|Pale grey,Blue-green,World-wide,NaN,0
77,Porlock,Porlock,XX,Black|Red|Brown,Blue,England|Ireland,24.0,0
78,Puffskein,Puffskein,XX,Custard,No data,No data,NaN,0
79,Flobberworm,Flobberworm,X,Brown,No data,No data,10.0,0
80,Horklump,Horklump,X,Pink|Black,No data,Scandinavia,NaN,0

Выведем информацию о типах столбцов, а также описательные статистики для числовых и текстовых столбцов датафрейма:

In [4]:
# в некоторых версиях вместо object стоит str,
# в любом случае это текстовый тип
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            81 non-null     str
 1   Class           81 non-null     str
 2   Classification  81 non-null     str
 3   Colour          81 non-null     str
 4   Eye             80 non-null     str
 5   Native          81 non-null     str
 6   Size            28 non-null     float64
 7   Dragon          81 non-null     int64
dtypes: float64(1), int64(1), str(6)
memory usage: 8.9 KB

In [5]:
# по умолчанию выбираются столбцы числовых типов,
# int и float, по ним считаются статистики

df.describe()

             Size     Dragon
count   28.000000  81.000000
mean   147.358929   0.123457
std    178.181732   0.331010
min      0.050000   0.000000
25%     11.500000   0.000000
50%     69.000000   0.000000
75%    189.000000   0.000000
max    600.000000   1.000000

> Здесь `count` – число заполненных ячеек, `mean` – среднее, `std` – стандартное отклонение, `min` и `max` – минимум и максимум, `25%`, `50%` и `75%` – нижний квартиль, медиана и верхний квартиль.

In [6]:
# если хотим описание текстовых столбцов,
# добавляем аргумент include = "object",
# поскольку в будущей более новой версии pandas
# название "object" заменят на "str", 
# выводится предупреждение, но код работает

df.describe(include = "object")

/var/folders/97/r7qrmy8d3_x75p950vm92w0r0000gn/T/ipykernel_14887/854087107.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object")

               Name   Class Classification Colour      Eye      Native
count            81      81             81     81       80          81
unique           81      72              5     53       17          45
top     Acromantula  Dragon            XXX  Green  No data  World-wide
freq              1      10             27      7       34          10

> Здесь `count` – число заполненных ячеек, `unique` – число уникальных (разных) значений, `top` – мода, самое частое значение, `freq` – частота, соответствующая моде. Например, в столбце `Classification` больше всего значений `XXX` (третий класс опасности), их 27.

Выберем отдельный столбец и опишем его:

In [7]:
df["Size"].describe()

count     28.000000
mean     147.358929
std      178.181732
min        0.050000
25%       11.500000
50%       69.000000
75%      189.000000
max      600.000000
Name: Size, dtype: float64

> Для выбора столбца его название указывается в квадратных скобках в кавычках. Такой синтаксис объясняется тем, что в Python объект типа `pandas DataFrame` изнутри выглядит как словарь (базовый тип `dictionary` или просто `dict`). Словарь – набор пар «ключ-значение», и выбор значений производится по ключу. Так, таблица в `df` в «сыром» виде похожа на словарь, где ключами выступают названия столбцов, а значениями – столбцы с данными:

    {"Name" : np.array(["Acromantula", "Basilisk", "Chimaera", ...]), 
    "Class" : np.array(["Acromantula", "Basilisk", "Chimaera", ...]),
    "Classification" : np.array(["XXXXX", "XXXXX", "XXXXX", ...])}

Если написать `df[Size]`, мы получим ошибку `NameError`, так как без кавычек Python будет воспринимать `Size` как название переменной, а мы такой переменной не создавали. Если написать просто `"Size"` без `df`, для Python это просто текст со словом "Size".

**Дополнение.** Каждый столбец датафрейма – это объект типа `pandas Series`, то есть последовательность Pandas.

In [8]:
df["Dragon"]

0     0
1     0
2     0
3     1
4     1
     ..
76    0
77    0
78    0
79    0
80    0
Name: Dragon, Length: 81, dtype: int64

Этот объект – «усовершенствованный» массив NumPy. Он состоит из двух частей – индексы элементов (0, 1, ..., 80) и сами элементы. Индексы элементов хранятся в атрибуте `.index`, а значения – в атрибуте `.values`:

In [9]:
# .index – отдельный тип RangeIndex
# .values – массив NumPy

print(df["Dragon"].index)
print(df["Dragon"].values)

RangeIndex(start=0, stop=81, step=1)
[0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]

Для фильтрации строк или добавления новых столбцов забирать элементы отдельно через `.values` не потребуется, однако понимание внутреннего устройства столбца датафрейма позволит понять, почему в некоторых методах (например, для сортировки) нужно уточнять, с чем мы работаем, с индексами или самими значениями.

### Задача 1

Выберите строки, соответствующие драконам, и сохраните эти строки в датафрейм `dragons`.

In [10]:
dragons = df[df["Dragon"] == 1]
dragons

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
3,Antipodean Opaleye,Dragon,XXXXX,Pearly,Multi-coloured,New Zealand,NaN,1
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
5,Common Welsh Green,Dragon,XXXXX,Green,No data,Wales,216.0,1
6,Hebridean Black,Dragon,XXXXX,Dark,Brilliant purple,Scotland,360.0,1
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1
8,Norwegian Ridgeback,Dragon,XXXXX,Dark green,No data,Norway,NaN,1
9,Peruvian Vipertooth,Dragon,XXXXX,Copper,No data,Peru,180.0,1
10,Romanian Longhorn,Dragon,XXXXX,Dark green,No data,Romania,480.0,1
11,Swedish Short-Snout,Dragon,XXXXX,Silvery blue,No data,Sweden,264.0,1
12,Ukrainian Ironbelly,Dragon,XXXXX,Metallic grey-silver,Deep red,Ukraine,NaN,1

### Задача 2

Выберите строки, соответствующие существам из Греции или Румынии (*Greece* или *Romania* в `Native`). Вычислите их количество.

In [11]:
df2 = df[(df["Native"] == "Greece") | (df["Native"] == "Romania")]
print(len(df2))

7

### Задача 3

Выберите строки, соответствующие существам размером более 500 дюймов.

In [12]:
df3 = df[df["Size"] > 500]
df3

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1

### Задача 4

Выберите строки, соответствующие существам размером от 100 до 200 дюймов включительно.

In [13]:
df4 = df[(df["Size"] >= 100) & (df["Size"] <= 200)]
df4

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
0,Acromantula,Acromantula,XXXXX,Jet-Black,Black,Island of Borneo,180.0,0
9,Peruvian Vipertooth,Dragon,XXXXX,Copper,No data,Peru,180.0,1
27,Occamy,Occamy,XXXX,Turquoise|Purple|Teal,No data,Far East|India,180.0,0
35,Troll,Troll,XXXX,Varies,Varies,Europe,144.0,0
37,Yeti,Yeti,XXXX,Grey|White,No data,Tibet,180.0,0
52,Lobalug,Lobalug,XXX,Yellow,No data,North Sea,120.0,0

### Задача 5

Выберите строки, соответствующие драконам размером менее 300 дюймов.

In [14]:
df5 = df[(df["Dragon"] == 1) & (df["Size"] < 300)]
df5

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
5,Common Welsh Green,Dragon,XXXXX,Green,No data,Wales,216.0,1
9,Peruvian Vipertooth,Dragon,XXXXX,Copper,No data,Peru,180.0,1
11,Swedish Short-Snout,Dragon,XXXXX,Silvery blue,No data,Sweden,264.0,1

### Задача 6

Выберите строки, соответствующие существам с классом Министерства Магии не ниже 4 и имеющим желтые глаза (`Yellow`). Сохраните эти строки в датафрейм `dang_yellow`.

In [15]:
# внимание на дополнительные круглые скобки вокруг
# условий с ИЛИ – для порядка действий

dang_yellow = df[((df["Classification"] == "XXXX") | 
                  (df["Classification"] == "XXXXX")) & 
    (df["Eye"] == "Yellow")]
dang_yellow

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1
20,Erkling,Erkling,XXXX,Green,Yellow,Germany,36.0,0
23,Griffin,Griffin,XXXX,Brownish-yellow|White|Brown,Yellow,Greece,NaN,0

In [16]:
# альтернативное решение
# метод .isin() проверяет, входит ли элемент в перечень

dang_yellow = df[df["Classification"].isin(["XXXX", "XXXXX"])
                   & (df["Eye"] == "Yellow")]
dang_yellow

,Name,Class,Classification,Colour,Eye,Native,Size,Dragon
1,Basilisk,Basilisk,XXXXX,Green,Yellow,Greece,600.0,0
4,Chinese Fireball,Dragon,XXXXX,Scarlet,Yellow,China,300.0,1
7,Hungarian Horntail,Dragon,XXXXX,Black,Yellow,Hungary,600.0,1
20,Erkling,Erkling,XXXX,Green,Yellow,Germany,36.0,0
23,Griffin,Griffin,XXXX,Brownish-yellow|White|Brown,Yellow,Greece,NaN,0

**Дополнение.** В этих вариантах решения мы пока не рассматриваем подсчет количества символов в ячейках столбца `Classification` (об этом поговорим в следующий раз), а пользуемся тем, что не ниже 4 – это `XXXX` или `XXXXX`. Чтобы убедиться, что других значений нет, можем запросить таблицу частот через метод `.value_counts()`:

In [17]:
df["Classification"].value_counts()

Classification
XXX      27
XXXX     20
XXXXX    18
XX       14
X         2
Name: count, dtype: int64

По умолчанию используется сортировка записей по убыванию частот – самое частое значение в столбце `XXX`, оно встречается 27 раз, далее идет `XXXX` – встречается 20 раз, и так далее. Если мы хотим отсортировать категории по алфавиту (здесь от `X` до `XXXXX`), потребуется метод `.sort_index()`:

In [18]:
df["Classification"].value_counts().sort_index()

Classification
X         2
XX       14
XXX      27
XXXX     20
XXXXX    18
Name: count, dtype: int64

Почему именно `.sort_index()`, а не просто `.sort()`? Результат `.value_counts()` – отдельный столбец, последовательность `pandas Series`, состоящая из двух частей, из индексов и значений. Поэтому при сортировке надо уточнять, на основании чего упорядочивать элементы.

In [19]:
# разберем на части результат .value_counts()
# ровно то, что было перед задачей 1
# круг замкнулся :)

tab = df["Classification"].value_counts()
print(tab.index)
print(tab.values)

Index(['XXX', 'XXXX', 'XXXXX', 'XX', 'X'], dtype='str', name='Classification')
[27 20 18 14  2]

In [20]:
# сортировка по индексам vs сортировка по значениям
# по умолчанию по алфавиту или по возрастанию 

print(tab.sort_index())
print(tab.sort_values())

Classification
X         2
XX       14
XXX      27
XXXX     20
XXXXX    18
Name: count, dtype: int64
Classification
X         2
XX       14
XXXXX    18
XXXX     20
XXX      27
Name: count, dtype: int64