# Введение в регрессионный анализ: интенсив по Python

*Алла Тамбовцева*

## Семинар 8.2. Группировка и агрегирование в `pandas`

В файле `elections_agg.xlsx` (скачать [здесь](https://disk.yandex.ru/d/PDW3Vb3HXBeO3g)) сохранены результаты выборов в Государственную Думу в разрезе территориальных избирательных комиссий (одна строка – одна комиссия). Переменные в файле:

* `okrug`: название федерального округа;
* `region`: название региона;
* `tik`: название ТИК;
* `total`: число зарегистрированных избирателей;
* `turnout`: явка.

Далее – столбцы с числом голосов за партии:

* `КПРФ`: политическая партия "КОММУНИСТИЧЕСКАЯ ПАРТИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ";
* `ЗЕЛЕНЫЕ`: политическая партия "Российская экологическая партия "ЗЕЛЁНЫЕ";
* `ЛДПР`: политическая партия ЛДПР – Либерально-демократическая партия России;
* `НЛ`: политическая партия "НОВЫЕ ЛЮДИ";
* `ЕР`: всероссийская политическая партия "ЕДИНАЯ РОССИЯ";
* `СР`: партия СПРАВЕДЛИВАЯ РОССИЯ – ЗА ПРАВДУ;
* `ЯБЛОКО`: политическая партия "Российская объединенная демократическая партия "ЯБЛОКО";
* `ПР`: всероссийская политическая партия "ПАРТИЯ РОСТА";
* `РПСС`: политическая партия РОССИЙСКАЯ ПАРТИЯ СВОБОДЫ И СПРАВЕДЛИВОСТИ;
* `КР`: политическая партия КОММУНИСТИЧЕСКАЯ ПАРТИЯ КОММУНИСТЫ РОССИИ;
* `ГП`: политическая партия "Гражданская Платформа";
* `ЗА`: политическая партия ЗЕЛЕНАЯ АЛЬТЕРНАТИВА;
* `РОДИНА`: "ВСЕРОССИЙСКАЯ ПОЛИТИЧЕСКАЯ ПАРТИЯ "РОДИНА".

Далее – столбцы с процентами голосов за партии (`КПРФ%` - `РОДИНА%`).

In [1]:
import pandas as pd

Загрузите данные из файла `elections_agg.xlsx` и сохраните в датафрейм `data`. Используйте функцию `read_excel()` из `pandas`.

In [3]:
data = pd.read_excel("elections_agg.xlsx")
data

,Unnamed: 0,okrug,region,tik,total,turnout,КПРФ,ЗЕЛЕНЫЕ,ЛДПР,НЛ,...,НЛ%,ЕР%,СР%,ЯБЛОКО%,ПР%,РПСС%,КР%,ГП%,ЗА%,РОДИНА%
0,0,Сибирский федеральный округ,Алтайский край,Алейская,11743,6861,1557,32,743,213,...,3.104504,48.156245,6.777438,0.480979,0.160326,0.495555,2.040519,0.145751,0.276928,0.393529
1,1,Сибирский федеральный округ,Алтайский край,Алейская городская,21076,9590,2556,53,906,465,...,4.848801,40.198123,7.924922,0.677789,0.208551,0.500521,2.950991,0.072993,0.594369,0.396246
2,2,Сибирский федеральный округ,Алтайский край,Алтайская,19006,8531,2519,45,821,573,...,6.716680,36.256008,8.263978,0.363381,0.199273,0.480600,2.449889,0.046888,0.281327,0.281327
3,3,Сибирский федеральный округ,Алтайский край,Баевская,7654,3649,1465,22,311,124,...,3.398191,32.967936,5.727597,0.301452,0.164429,0.383667,2.247191,0.027405,0.219238,0.465881
4,4,Сибирский федеральный округ,Алтайский край,"Барнаул, Вторая Индустриальная",95660,30619,10368,307,2140,2981,...,9.735785,28.436592,8.919298,1.848525,0.316797,0.594402,1.851791,0.035925,0.679317,1.136549
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846,2846,Южный федеральный округ,город Севастополь,Балаклавская,42846,19947,2293,169,1750,632,...,3.168396,61.247305,7.058706,0.596581,0.230611,0.506342,0.772046,0.060159,0.355943,0.521382
2847,2847,Южный федеральный округ,город Севастополь,Гагаринская,107421,41345,6127,620,3560,2098,...,5.074374,53.493772,8.644334,0.662716,0.319265,0.679647,0.643367,0.072560,0.544201,0.919095
2848,2848,Южный федеральный округ,город Севастополь,Дистанционное электронное голосование,20772,18621,1754,814,1793,1399,...,7.513023,53.788733,8.377638,0.767950,0.445733,0.703507,0.601471,0.102035,1.428495,0.773320
2849,2849,Южный федеральный округ,город Севастополь,Ленинская,83249,43298,5281,551,3145,1992,...,4.600674,58.947295,7.487644,0.739064,0.367223,0.706730,0.792184,0.309483,0.776017,0.884567
2850,2850,Южный федеральный округ,город Севастополь,Нахимовская,83820,42024,5390,454,3919,2636,...,6.272606,55.680088,6.410623,0.568723,0.302208,0.530649,0.835237,0.071388,0.704359,0.606796

### Задача 1

* Добавьте в `data` столбец `КП%` – сумму процентов голосов за коммунистические партии (КПРФ и «Коммунисты России»). 

* Добавьте в `data` столбец `ЭКО%` – суммы процентов за экологические партии («Зеленые» и «Зеленая альтернатива»).

In [4]:
# вообще можно просто сложить два столбца с процентами за эти партии,
# но мы на семинаре для практики сложили столбцы с бюллетенями и поделили на явку

data["КП%"] = (data["КПРФ"] + data["КР"]) / data["turnout"] * 100
data["ЭКО%"] = (data["ЗЕЛЕНЫЕ"] + data["ЗА"]) / data["turnout"] * 100

### Задача 2

Сгруппируйте строки в `data` по федеральному округу и выведите описательные статистики для процента голосов за экологические партии.

In [5]:
data.groupby("okrug")["ЭКО%"].describe()

,count,mean,std,min,25%,50%,75%,max
okrug,,,,,,,,
Дальневосточный федеральный округ,247.0,1.404414,0.724282,0.247831,0.926710,1.290457,1.692985,6.052963
Приволжский федеральный округ,619.0,0.932027,0.621506,0.021186,0.510307,0.783766,1.175885,4.807692
Северо-Западный федеральный округ,276.0,1.769428,0.682310,0.391645,1.231165,1.723759,2.263234,4.704859
Северо-Кавказский федеральный округ,154.0,0.423929,0.368370,0.000000,0.141571,0.337186,0.553349,1.883122
Сибирский федеральный округ,388.0,1.448927,1.236933,0.000000,0.785192,1.030726,1.740366,8.543923
Уральский федеральный округ,223.0,1.185922,0.571916,0.072089,0.814474,1.062253,1.504902,3.256361
Центральный федеральный округ,697.0,1.545484,1.018030,0.028023,0.795707,1.257835,2.190337,6.187596
Южный федеральный округ,247.0,1.007478,0.630407,0.044900,0.581088,0.881057,1.314038,5.799903

### Задача 3

Сгруппируйте строки в `data` по региону, выберите столбцы `turnout` и `total`, посчитайте по ним сумму. Полученную таблицу сохраните в переменную `data_agg`.

In [8]:
data_agg = data.groupby("region")[["turnout", "total"]].sum()
data_agg

                                 turnout    total
region
Алтайский край                    739460  1806679
Амурская область                  254658   612971
Архангельская область             364779   877875
Астраханская область              315458   725572
Белгородская область              724020  1226298
...                                  ...      ...
Ямало-Ненецкий автономный округ   253294   376862
Ярославская область               434921  1006556
город Москва                     3845170  7770014
город Санкт-Петербург            1470062  3939917
город Севастополь                 165235   338108

[85 rows x 2 columns]

### Задача 4

* Добавьте в `data_agg` столбец `turnout%` с явкой в процентах.
* Вычислите среднее по полученному столбцу и сохраните в переменную `avg`.
* Добавьте в `data_agg` столбец `high` из 0 и 1, где 1 ставится, если явка в процентах в регионе выше средней.

In [9]:
data_agg["turnout%"] = data_agg["turnout"] / data_agg["total"] * 100
data_agg

                                 turnout    total   turnout%
region
Алтайский край                    739460  1806679  40.929241
Амурская область                  254658   612971  41.544869
Архангельская область             364779   877875  41.552499
Астраханская область              315458   725572  43.477146
Белгородская область              724020  1226298  59.041114
...                                  ...      ...        ...
Ямало-Ненецкий автономный округ   253294   376862  67.211340
Ярославская область               434921  1006556  43.208823
город Москва                     3845170  7770014  49.487298
город Санкт-Петербург            1470062  3939917  37.312004
город Севастополь                 165235   338108  48.870479

[85 rows x 3 columns]

In [10]:
avg = data_agg["turnout%"].mean()
print(avg)

52.128249922829575

In [11]:
data_agg["high"] = (data_agg["turnout%"] > avg).astype(int)
data_agg

                                 turnout    total   turnout%  high
region
Алтайский край                    739460  1806679  40.929241     0
Амурская область                  254658   612971  41.544869     0
Архангельская область             364779   877875  41.552499     0
Астраханская область              315458   725572  43.477146     0
Белгородская область              724020  1226298  59.041114     1
...                                  ...      ...        ...   ...
Ямало-Ненецкий автономный округ   253294   376862  67.211340     1
Ярославская область               434921  1006556  43.208823     0
город Москва                     3845170  7770014  49.487298     0
город Санкт-Петербург            1470062  3939917  37.312004     0
город Севастополь                 165235   338108  48.870479     0

[85 rows x 4 columns]

In [12]:
# можем дополнительно посчитать число регионов с явкой выше среднего

print(data_agg["high"].sum())

28

### Задача 5

Отсортируйте строки в `data_agg` по убыванию явки в процентах и сохраните изменения.

In [13]:
# раз сохраняем изменения, можм перезаписать переменную data_agg

data_agg = data_agg.sort_values("turnout%", ascending = False)
data_agg

                                     turnout    total   turnout%  high
region
Чеченская Республика                  731968   775256  94.416296     1
Карачаево-Черкесская Республика       268928   301151  89.300052     1
Республика Северная Осетия - Алания   450520   520743  86.514845     1
Кабардино-Балкарская Республика       462254   539787  85.636371     1
Республика Дагестан                  1435096  1699609  84.436832     1
...                                      ...      ...        ...   ...
Владимирская область                  417788  1103455  37.861807     0
Новосибирская область                 815311  2161918  37.712392     0
Республика Хакасия                    148110   394707  37.524037     0
город Санкт-Петербург                1470062  3939917  37.312004     0
Иркутская область                     688367  1861964  36.969941     0

[85 rows x 4 columns]